### ISSUE TITLE
<modal-portal> is already created error with Nuxt

### ISSUE THREAD

**Issue by kiaking** [ktsn/vue-thin-modal#12]
Hi! Wonderful piece of the library here! I love it and thank you so much for sharing this.

Have you ever tried using this library with Nuxt (I'm using Nuxt v2.0.0)? Since I'm having a trouble where if I refresh the page, I get an error displayed.

I've defined plugin as below;

```js
// @/plugins/vue-thin-modal.js

import Vue from 'vue'
import VueThinModal from 'vue-thin-modal'

Vue.use(VueThinModal, { autoMountPortal: false })
```

Then defined `<modal-portal>` at default layout file.

```vue
<template>
  <div class="App">
    <div class="content">
      <nuxt />
    </div>

    <modal-portal />
  </div>
</template>
```

Now when I serve nuxt locally, and then access the page, at first it works but if I refresh the page, I get `[vue-thin-modal] <modal-portal> is already created.` error.

Do you have any idea what is going on here?

**Comment by ktsn** [comment]
Thanks for the report! This looks because of too strict assertion for `<modal-portal>`. Currently, vue-thin-modal not expect two or more `<modal-portal>` instance. But on the SSR environment, there may be a case because the server shares the context among sessions.

I think we can use `<modal>` and `<modal-portal>` without `<no-ssr>` component after fixing vue-thin-modal.

**Comment by kiaking** [comment]
Oh OK! That's wonderful! I'll be waiting for the fix then : ) Meanwhile, I'll get over with this issue by using `no-ssr`. Thank you for your support!

**Comment by kiaking** [comment]
Man that was quick 👍

**Comment by ktsn** [comment]
Just shipped v1.1.2 including the fix 🎉

**Comment by kiaking** [comment]
Hooray! :tada:

**Comment by remarks** [comment]
Hi! I'm replicating this issue when you switch between layouts, both with `<modal-portal />`.

It looks like since it's exiting the first layout, it's trying to destroy the instance, then re-initialize the one on the second layout: 

![screen shot 2018-10-23 at 11 48 12 pm](https://user-images.githubusercontent.com/1432193/47411618-300dc680-d71e-11e8-827c-e3907ec02d4a.png)
